import type { Metadata, Viewport } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeApplier } from "@/components/ThemeApplier";
import { THEME_STORAGE_KEY } from "@/lib/themeStore";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// viewportFit: "cover" is what makes env(safe-area-inset-*) return real
// values on notched devices — without it the insets are always 0 and the
// footer/toolbar would clip under the notch / home indicator. width +
// initialScale keep the default responsive behavior; scaling stays enabled
// for accessibility (the 3D canvas gets its own touch-action via
// OrbitControls, so pinch there controls the camera, not the page).
export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover",
};

// Runs synchronously in <head>, before React hydrates or first paint —
// reads the same localStorage key lib/themeStore.ts persists to and stamps
// data-theme/data-mode onto <html> immediately, so the correct theme's CSS
// variables (app/globals.css) are already active for first paint. Without
// this, the page would render in the default theme for a frame and then
// visibly snap to the user's saved choice once the zustand store hydrates.
const THEME_INIT_SCRIPT = `
(function () {
  try {
    var raw = localStorage.getItem(${JSON.stringify(THEME_STORAGE_KEY)});
    var state = raw ? JSON.parse(raw).state : null;
    var theme = (state && state.theme) || "sage";
    var mode = (state && state.mode) || "dark";
    document.documentElement.dataset.theme = theme;
    document.documentElement.dataset.mode = mode;
  } catch (e) {}
})();
`;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script dangerouslySetInnerHTML={{ __html: THEME_INIT_SCRIPT }} />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeApplier />
        {children}
      </body>
    </html>
  );
}
